remote_theme: "mmistakes/so-simple-theme@3.2.0"
title: Katie Knish
description: I'm a technical writer based in the Upper Valley in Vermont. This site is a hub for samples and projects. Thanks for visiting!
plugins:
  - jekyll-remote-theme